### ISSUE TITLE
Does cfdev download anything, on every start?

### ISSUE THREAD

**Issue by akoranne** [pivotal-cf/cfdev#10]
I downloaded `cfdev`. First time, as expected, it took a long time. 

But on subsequent restarts (after stopping) of cf dev, it is taking 20+ minutes to start.
It already has the iso in ~/.cfdev/cache folder.
Does it download any bits on every restart?

**Comment by akoranne** [comment]
```
 2018-03-01 07:56:06 ⌚in ~/Workspaces
○ → cf dev start
Downloading Resources...
Starting VPNKit ...
Starting the VM...
Deploying the BOSH Director...
Deploying CF...

  ██████╗███████╗██████╗ ███████╗██╗   ██╗
 ██╔════╝██╔════╝██╔══██╗██╔════╝██║   ██║
 ██║     █████╗  ██║  ██║█████╗  ██║   ██║
 ██║     ██╔══╝  ██║  ██║██╔══╝  ╚██╗ ██╔╝
 ╚██████╗██║     ██████╔╝███████╗ ╚████╔╝
  ╚═════╝╚═╝     ╚═════╝ ╚══════╝  ╚═══╝
             is now running!

To begin using CF Dev, please run:
    cf login -a https://api.v3.pcfdev.io --skip-ssl-validation

Admin user => Email: admin / Password: admin
Regular user => Email: user / Password: pass


 2018-03-01 08:16:11 ⌚in ~/Workspaces
```

**Comment by ekcasey** [comment]
Hi @akoranne 

CF Dev will not re-download the resources. On each start, it will redeploy a bosh director to the garden instance running in the vm and then use that bosh director to deploy CloudFoundry. It uses pre-compiled bosh releases from the iso in the cache folder, but it can still take some time to deploy.

**Comment by akoranne** [comment]
Thank you @ekcasey
