### ISSUE TITLE
Deploying concourse to cfdev

### ISSUE THREAD

**Issue by akoranne** [pivotal-cf/cfdev#12]
This is not an issue, but was wondering if anyone has successfully done it. 
Is tweaking the concourse manifest to map to the cloud config do the trick? 
Or anything else would be required? Just looking at concourse.
Will look at credhub etc later.

**Comment by drnic** [comment]
I would expect cfdev to operate like any bosh-lite?

________________________________

**Comment by sclevine** [comment]
CF Dev uses the Warden CPI (with some usability improvements) to provide a compatible experience with BOSH lite. If you can deploy Concourse to BOSH lite, you should be able to deploy it to CF Dev.

**Comment by akoranne** [comment]
Thank you @sclevine. I will give it a try.
