### ISSUE TITLE
Spring Cloud Service 

### ISSUE THREAD

**Issue by amitoj** [pivotal-cf/cfdev#13]
Is there a flag to configure SCS on cfdev?

**Comment by ekcasey** [comment]
Hi @amitoj at this time there is no built in support for scs on `cfdev`. Support for services including scs is on the roadmap.

You could provide the services you need to your apps as user provided services https://docs.cloudfoundry.org/devguide/services/user-provided.html.

Alternatively, you could deploy the scs broker to cfdev yourself. The new cfdev comes with a bosh director! The `cf dev bosh` command provides instructions for targeting that director. If you need scs in cfdev and you have access to the bosh releases you could deploy and register the scs broker and it's dependencies (this would require some effort and I would only recommend it if you are comfortable with bosh).

**Comment by sclevine** [comment]
Worth noting: Spring Cloud Services for PCF is a Pivotal product that will be included in the separate PCF integration for CF Dev. It will not be included in the official Cloud Foundry distribution of CF Dev, which will only include open source Cloud Foundry components and services.

**Comment by amitoj** [comment]
Is the support for Spring Cloud Services included in pcfdev-pas.v.2.1.0-build.0.8.0.dev?
