### ISSUE TITLE
Installation fails on archlinux 

### ISSUE THREAD

**Issue by reachrkr** [pivotal-cf/cfdev#2]
Downloaded the plugin and tried installing  it failed on my linux box . Error below 

-----------------------------------------------------------------------------------------------------
[ ~]$ cf install-plugin ~/Downloads/cfdev-v0.1-darwin 
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin /home/rajesh/Downloads/cfdev-v0.1-darwin? [yN]
: y
fork/exec /home/rajesh/.cf/plugins/temp575906849/805106444: exec format error
File is not a valid cf CLI plugin binary.
FAILED

-----------------------------------------------------------------------------------------------------
[~]$ uname -r
4.15.3-2-ARCH

-----------------------------------------------------------------------------------------------------

**Comment by sclevine** [comment]
This first alpha release is for macOS-only. Support for Linux via KVM is on the roadmap.
