### ISSUE TITLE
Error downloading resources after installing the plugin

### ISSUE THREAD

**Issue by vinayu** [pivotal-cf/cfdev#3]
Vinay-Upadhya-MacBook-Pro:Downloads vupadhya$ cf install-plugin cfdev-v0.0.1-darwin

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin cfdev-v0.0.1-darwin?> yes

Installing plugin cfdev-v0.0.1-darwin...
OK
Plugin cfdev v0.0.1 successfully installed.
Vinay-Upadhya-MacBook-Pro:Downloads vupadhya$ cf dev start
Setting up IP aliases for the BOSH Director & CF Router (requires root privileges)
Password:
Downloading Resources...
Error encountered running 'start' : Unable to sync assets: read tcp 192.168.0.201:49708->13.33.46.10:443: read: connection reset by peer

**Comment by sclevine** [comment]
Hi @vinayu, do you use an enterprise HTTP proxy?

**Comment by vinayu** [comment]
No. It's on my home laptop & network.

**Comment by vinayu** [comment]
Closing this github issue as it was mostly an issue related to my internet.
