### ISSUE TITLE
Support for VMware Hypervisors

### ISSUE THREAD

**Issue by jeremyrickard** [pivotal-cf/cfdev#4]
It looks like the wrappers around LinuxKit are currently only supporting HyperKit? I assume right now this is mac-Os only. Does your roadmap currently have any plans for supporting Fusion/Workstation?

**Comment by jeremyrickard** [comment]
BTW would be happy to try and contribute this!

**Comment by sclevine** [comment]
Hi @jeremyrickard,

What's your use case for Fusion or Workstation? We have Hyper-V support for Windows 10 lined up next.

We're planning to implement a legacy OVA distribution for Windows 7 and other older platforms. This OVA will work in Virtualbox and VMware Fusion/Workstation, but it will be limited (ex. it must be used entirely inside the VM and it won't include a CLI plugin).

**Comment by jeremyrickard** [comment]
Purely preference, I have HyperV disabled on my Surface (using Workstation instead). Fusion isn't a really big deal for me, other than my preference of managing that all my virtualized stuff via Fusion (and sometimes migrating it to one of my ESXi boxes). The OVA thing would probably be sufficient for my Workstation and ESXi needs. Thanks!
